image: node

before_script:
  - npm install

deploy:
  stage: deploy
  script:
    - node_modules/.bin/gatsby build
    - cp CNAME public/
    - node_modules/.bin/surge public/
  only:
    - master

test_staging:
  stage: deploy
  script:
    - node_modules/.bin/gatsby build
    - cp DEV_CNAME public/
    - node_modules/.bin/surge public/