image: node

before_script:
  - npm install

deploy_staging:
  stage: deploy
  environment:
    - name: staging
    - url: nttc.surge.sh
  script:
    - node_modules/.bin/gatsby build
    - cp DEV_CNAME public/CNAME
    - node_modules/.bin/surge public/
  only:
    - branches
  except:
    - master

deploy:
  stage: deploy
  script:
    - node_modules/.bin/gatsby build
    - cp CNAME public/
    - node_modules/.bin/surge public/
  only:
    - master