backend:
  name: git-gateway
  branch: master #branch to update (optional; defaults to master)
publish_mode: editorial_workflow #allows for a drafting, reviewing, and approving process for changes
media_folder: "src/assets/images/uploads"
public_folder: "/images"

#collections
collections:
  - label: "Upcoming Schedule Changes"
    name: "upcoming schedule changes"
    files:
      - label: "Cancellations"
        name: "cancellations"
        file: "static/content/cancellations.md"
        fields:
        - label: "Cancellations"
          name: "cancellations"
          create: true
          widget: "list"
          fields:
            - {label: "Date", name: "date", widget: "date"}
            - {label: "Day", name: "day", widget: "select", options: ["Thursday", "Friday", "Sunday"]}
            - {label: "Location", name: "location", widget: "select", options: ["Nolensville Rec Center", "Academy Park", "Indoor Sports Complex"]}
            - {label: "Type", name: "type", widget: "select", options: ["Cancelled", "Delayed", "Relocated"]}